// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFKDpCiwIRfyNuBSEh_XWLY49-jjjv7g',
    appId: '1:665069224037:android:2578f21be1c0d800fe468c',
    messagingSenderId: '665069224037',
    projectId: 'sba7o-a24b3',
    storageBucket: 'sba7o-a24b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTC0q3WC03HlG7NQuzc13tWaWi-Ja-N7g',
    appId: '1:665069224037:ios:2d329be8c8993e0ffe468c',
    messagingSenderId: '665069224037',
    projectId: 'sba7o-a24b3',
    storageBucket: 'sba7o-a24b3.appspot.com',
    androidClientId: '665069224037-3f7b66gvllaaktonm6betppptbgef54e.apps.googleusercontent.com',
    iosClientId: '665069224037-d0l0jhdu3a77icvl93rm6htm2l5n74el.apps.googleusercontent.com',
    iosBundleId: 'com.example.superApp',
  );
}
