class SuperStringsClass{
  static const clueTime = 30;
  static const clubsTime = 30;
  static const mazaTime = 120;
  static const photoTime = 240;
  static const randomTime = 180;
  static const List<String> appAnswers = [
    'FIFA World Cup كاس العالم',
    'UEFA Champions League دوري ابطال اوروبا',
    'Copa Libertadores كوبا ليبرتادوريس',
    'Copa America كوبا امريكا',
    'UEFA European Championship (Euro) بطولة امم اوروبا',
    'African Cup of Nations كاس الامم الافريقية',
    'Asian Cup كاس اسيا',
    'CONCACAF Gold Cup كاس الامم الذهبية',
    'La Liga الدوري الاسباني',
    'Bundesliga الدوري الالماني',
    'Serie A الدوري الايطالي',
    'Ligue 1 الدوري الفرنسي',
    'Eredivisie الدوري الهولندي',
    'Jupiler Pro League الدوري البلجيكي',
    'CAF Champions League دوري ابطال افريقيا',
    'AFC Champions League دوري ابطال اسيا',
    'Premier League الدوري الانجليزي الممتاز',
    'الكونفيدرالية',
    'Al Ahly الاهلي',
    'Zamalek الزمالك',
    'Ismaily الاسماعيلي',
    'Pyramids بيراميدز',
    'Contractors المقاولون',
    'Smouha الاتحاد السكندري',
    'Military Production الانتاج الحربي',
    'Talaea El Gaish طلائع الجيش',
    'Misr Lel Makkasa مصر المقاصة',
    'Wadi Degla وادي دجلة',
    'Enppi انبي',
    'Al Masry المصري',
    'Aswan اسوان',
    'El Gouna الجونة',
    'Petrotoli بتروجت',
    'Al Ragaa الرجاء',
    'Smouha سموحة',
    'Home Club الداخلية',
    'Police Club الشرطة',
    'Shooting Club الصيد',
    'Cairo Club القاهرة',
    'Paris Saint Germain باريس سان جيرمان',
    'Marseille مارسيليا',
    'Lille ليل',
    'Lyon ليون',
    'Monaco موناكو',
    'Bordeaux بوردو',
    'Nice نيس',
    'Rennes رين',
    'Saint etienne سانت ايتيان',
    'Montpellier مونبلييه',
    'Lens لانس',
    'Nantes نانت',
    'Reims ريمس',
    'Strasbourg ستراسبورغ',
    'Metz ميتز',
    'Lorient لوريان',
    'Troyes تروا',
    'Clermont Foot كليرمون',
    'Bayern Munich بايرن ميونيخ',
    'Borussia Dortmund بوروسيا دورتموند',
    'Bayer Leverkusen باير ليفركوزن',
    'Leipzig راسينغ كلوب',
    'Borussia Monchengladbach بوروسيا مونشنغلادباخ',
    'Wolfsburg فولفسبورغ',
    'Freiburg فرايبورغ',
    'Augsburg اوغسبورغ',
    'Stuttgart شتوتغارت',
    'Arminia Bielefeld ارمينيا بيليفيلد',
    'Hoffenheim هوفنهايم',
    'Koln كولن',
    'Ingolstadt انجولشتاد',
    'Gruether Furth غرويتر فورت',
    'Union Berlin اونيون برلين',
    'Bochum بوخوم',
    'Mainz ماينز',
    'Schalke شالكه',
    'Hertha Berlin هيرتا برلين',
    'Juventus يوفنتوس',
    'Inter انتر',
    'AC Milan ميلان',
    'AS Roma روما',
    'Napoli نابولي',
    'Lazio لاتسيو',
    'Atalanta اتالانتا',
    'Fiorentina فيورنتينا',
    'Sampdoria سامبدوريا',
    'Torino تورينو',
    'Bologna بولونيا',
    'Genoa جنوي',
    'Udinese اودينيزي',
    'Spezia سبيزيا',
    'Cagliari كالياري',
    'Verona هيلاس',
    'Sassuolo ساسولو',
    'Parma بارما',
    'Crotone كروتوني',
    'Benevento بينيفينتو',
    'Atletico Madrid اتلتيكو مدريد',
    'Barcelona برشلونة',
    'Real Madrid ريال مدريد',
    'Valencia فالنسيا',
    'Sevilla اشبيلية',
    'Villarreal فياريال',
    'Real Betis ريال بيتيس',
    'Celta Vigo سيلتا فيغو',
    'Athletic Bilbao اتلتيك بيلباو',
    'Real Sociedad ريال سوسيداد',
    'Osasuna اوساسونا',
    'Eibar ايبار',
    'Alaves الافيس',
    'Getafe خيتافي',
    'Cadiz كاديز',
    'Real Valladolid ريال فيا',
    'Elche التشي',
    'Huesca هويسكا',
    'Mallorca مايوركا',
    'Arsenal ارسنال',
    'Aston Villa استون فيلا',
    'Brighton & Hove Albion برايتون وهوف البيون',
    'Brentford برنتفورد',
    'Burnley بيرنلي',
    'Chelsea تشيلسي',
    'Crystal Palace كريستال بالاس',
    'Everton ايفرتون',
    'Leeds United ليدز يونايتد',
    'Leicester City ليستر سيتي',
    'Liverpool ليفربول',
    'Manchester City مانشستر سيتي',
    'Manchester United مانشستر يونايتد',
    'Newcastle United نيوكاسل يونايتد',
    'Norwich City نوريتش سيتي',
    'Southampton ساوثهامبتون',
    'Tottenham Hotspur توتنهام هوتسبير',
    'Watford واتفورد',
    'West Ham United وست هام يونايتد',
    'Wolverhampton Wanderers ولفرهامبتون واندررز',
    'Afghanistan افغانستان',
    'Bahrain البحرين',
    'Bangladesh بنغلاديش',
    'Bhutan بوتان',
    'Brunei بروناي',
    'Cambodia كمبوديا',
    'China الصين',
    'Taiwan تايوان',
    'Timor Leste شرق تيمور',
    'India الهند',
    'Indonesia اندونيسيا',
    'Iran ايران',
    'Iraq العراق',
    'Japan اليابان',
    'Jordan الاردن',
    'Kazakhstan كازاخستان',
    'North Korea كوريا الشمالية',
    'South Korea كوريا الجنوبية',
    'Kuwait الكويت',
    'Kyrgyzstan قرغيزستان',
    'Laos لاوس',
    'Lebanon لبنان',
    'Malaysia ماليزيا',
    'Maldives جزر المالديف',
    'Mongolia منغوليا',
    'Myanmar ميانمار',
    'Nepal نيبال',
    'Oman عمان',
    'Pakistan باكستان',
    'Palestine فلسطين',
    'Philippines الفلبين',
    'Qatar قطر',
    'Saudi Arabia السعودية',
    'Singapore سنغافورة',
    'Sri Lanka سريلانكا',
    'Syria سوريا',
    'Tajikistan طاجيكستان',
    'Thailand تايلاند',
    'Turkmenistan تركمانستان',
    'United Arab Emirates الامارات العربية المتحدة',
    'Uzbekistan اوزبكستان',
    'Vietnam فيتنام',
    'Yemen اليمن',
    'Algeria الجزائر',
    'Angola انغولا',
    'Benin بنين',
    'Botswana بتسوانا',
    'Burundi بروندي',
    'Cameroon الكاميرون',
    'Cape Verde الراس الاخضر',
    'Central African Republic جمهورية افريقيا الوسطي',
    'Chad تشاد',
    'Comoros جزر القمر',
    'Congo الكونغو',
    'Djibouti جيبوتي',
    'Egypt مصر',
    'Equatorial Guinea غينيا الاستوائية',
    'Eritrea اريتريا',
    'Ethiopia اثيوبيا',
    'Gabon الغابون',
    'Gambia غامبيا',
    'Ghana غانا',
    'Guinea غينيا',
    'Guinea Bissau غينيا بيساو',
    'Ivory Coast كوت ديفوار',
    'Kenya كينيا',
    'Lesotho ليسوتو',
    'Liberia ليبيريا',
    'Libya ليبيا',
    'Madagascar مدغشقر',
    'Malawi مالاوي',
    'Mali مالي',
    'Mauritania موريتانيا',
    'Mauritius موريشيوس',
    'Morocco المغرب',
    'Mozambique موزمبيق',
    'Namibia ناميبيا',
    'Niger النيجر',
    'Nigeria نيجيريا',
    'Rwanda رواندا',
    'Saint Helena سانت هيلينا',
    'Senegal السنغال',
    'Seychelles سيشل',
    'Sierra Leone سيراليون',
    'Somalia الصومال',
    'South Africa جنوب افريقيا',
    'Sudan السودان',
    'South Sudan جنوب السودان',
    'Swaziland سوازيلاند',
    'Tanzania تنزانيا',
    'Togo توغو',
    'Tunisia تونس',
    'Uganda اوغندا',
    'Zambia زامبيا',
    'Zimbabwe زمبابوي',
    'Antigua and Barbuda انتيغوا وبربودا',
    'Argentina الارجنتين',
    'Bahamas بهاما',
    'Barbados باربادوس',
    'Belize بليز',
    'Bolivia بوليفيا',
    'Brazil البرازيل',
    'Canada كندا',
    'Chile تشيلي',
    'Colombia كولومبيا',
    'Costa Rica كوستاريكا',
    'Cuba كوبا',
    'Dominica الدومينيكا',
    'Dominican Republic جمهورية الدومينيكان',
    'Ecuador الاكوادور',
    'El Salvador سلفادور',
    'Grenada غرينادا',
    'Guatemala غواتيمالا',
    'Guyana غيانا',
    'Haiti هايتي',
    'Honduras هندوراس',
    'Jamaica جامايكا',
    'Mexico المكسيك',
    'Nicaragua نيكاراغوا',
    'Panama بنما',
    'Paraguay باراغواي',
    'Peru بيرو',
    'Saint Kitts and Nevis سانت كيتس ونيفيس',
    'Saint Lucia سانت لوسيا',
    'Saint Vincent and the Grenadines سانت فينسنت والغرينادينز',
    'Suriname سورينام',
    'Trinidad and Tobago ترينيداد وتوباغو',
    'United States الولايات المتحدة',
    'Uruguay اوروغواي',
    'Venezuela فنزويلا',
    'Sweden السويد',
    'Norway نرويج',
    'Finland فنلندا',
    'Ireland ايرلندا',
    'Lithuania ليتوانيا',
    'Latvia لاتفيا',
    'Estonia استونيا',
    'Bulgaria بلغاريا',
    'Greece اليونان',
    'Cyprus قبرص',
    'Malta مالطا',
    'Luxembourg لوكسمبورغ',
    'Moldova مولدوفا',
    'Belarus بيلاروسيا',
    'Bosnia and Herzegovina بوسنيا والهرسك',
    'Kosovo كوسوفو',
    'North Macedonia مقدونيا الشمالية',
    'Montenegro مونتينيغرو',
    'San Marino سان مارينو',
    'Vatican City فاتيكان',
    'Andorra اندورا',
    'Gibraltar جبل طارق',
    'Faroe Islands جزر فارو',
    'Iceland ايسلندا',
    "Frenkie de Jong رينكي دي يونج",
    "Clement Lenglet كليمان لينجليه",
    "Ousmane Dembele عثمان ديمبيلي",
    "Marc Andre ter Stegen مارك اندريه تير شتيجن",
    "Ivan Rakitic ايفان راكيتيتش",
    "Luis Suarez لويس سواريز",
    "Neymar نيمار",
    "Jordi Alba جوردي البا",
    "Sergi Roberto سيرجي روبيرتو",
    "Javier Mascherano خافيير ماسكيرانو",
    "David Villa دافيد فيا",
    "Adriano ادريانو كوريا",
    "Pedro بيدرو رودريجز",
    "Gerard Pique جيرارد بيكي",
    "Sergio Busquets سيرجيو بوسكيتس",
    "Seydou Keita سيدو كيتا",
    "Dani Alves داني الفيس",
    "Eric Abidal اريك ابيدال",
    "Yaya Toure يحيي توريه",
    "Bojan Krkic بويان كركيتش",
    "Thierry Henry تيري هينري",
    "Lilian Thuram ليليان تورام",
    "Gianluca Zambrotta جانلوكا زامبروتا",
    "Samuel Etoo صامويل ايتو",
    "Deco ديكو",
    "Rafael Marquez رافاييل ماركيز",
    "Giovanni van Bronckhorst جيوفاني فان برونكهورست",
    "Andres Iniesta اندريس انيستا",
    "Victor Valdes فيكتور فالديز",
    "Oleguer Presas اوليجر",
    "Javier Saviola خافيير سافيولا",
    "Thiago Motta تياجو موتا",
    "Carles Puyol كارليس بويول",
    "Gabri جابري جارسيا",
    "Xavi تشافي هيرنانديز",
    "Rivaldo ريفالدو",
    "Luis Enrique لويس انريكي",
    "Ronaldo الظاهرة رونالدو",
    "Luis Figo لويس فيجو",
    "Romario روماريو",
    "Pep Guardiola بيب جوارديولا",
    'Ronald Koeman رونالد كومان',
    'Luis de la Fuente لويس دي لا فوينتي',
    "Diego Maradona دييغو مارادونا",
    "Johan Cruyff يوهان كرويف",
    "Yannick Carrasco يانيك كاراسكو",
    "Thomas Partey توماس بارتي",
    "Stefan Savic ستيفان سافيتش",
    "angel Correa انخيل كوريا",
    "Lucas Hernandez لوكاس هيرنانديز",
    "Jan Oblak يان اوبلاك",
    "Antoine Griezmann انطوان جريزمان",
    "Nunez نونيز",
    "Jose Maria Gimenez خوسيه خيمينيز",
    "Saul niguez ساؤول نيجيز",
    "Radamel Falcao راداميل فالكاو",
    "Arda Turan اردا توران",
    "Miranda ميراندا",
    "Juanfran خوانفران",
    "Diego Costa دييجو كوستا",
    "Filipe Luis فيليبي لويس",
    "Diego Godin دييجو جودين",
    "Tiago Mendes تياجو مينديز",
    "Koke كوكي ريسوريكيون",
    "alvaro Dominguez الفارو دومينجيز",
    "Raul Garcia راؤول جارسيا",
    "Sergio Aguero سيرخيو اجويرو",
    "Fernando Torres فرناندو توريس",
    "Diego Simeone دييجو سيميوني",
    "Hakim Ziyech حكيم زياش",
    "Thiago Silva تياجو سيلفا",
    "Kai Havertz كاي هافيرتس",
    "edouard Mendy ادوارد ميندي",
    "Christian Pulisic كريستيان بوليسيتش",
    "Reece James ريس چيمس",
    "Kepa Arrizabalaga كيبا اريزابالاجا",
    "Mateo Kovacic ماتيو كوفاتشيتش",
    "Jorginho جورجينهو",
    "Ross Barkley روس باركلي",
    "Olivier Giroud اوليفيه جيرو",
    "Callum Hudson Odoi كالوم هودسون اودوي",
    "Mason Mount ماسون مونت",
    "Antonio Rudiger انطونيو روديجر",
    "NGolo Kante نجولو كانتي",
    "Marcos Alonso ماركوس الونسو",
    "Ruben Loftus Cheek روبن لوفتوس تشيك",
    "Andreas Christensen اندرياس كريستنسن",
    "Kurt Zouma كورت زوما",
    "Cesc Fabregas سيسك فابريجاس",
    "Willian ويليان",
    "Cesar Azpilicueta سيزار ازبيليكويتا",
    "Victor Moses فيكتور موسيس",
    "Eden Hazard ايدن هازارد",
    "Gary Cahill جاري كاهيل",
    "Oscar اوسكار",
    "David Luiz دافيد لويز",
    "Juan Mata خوان ماتا",
    "Nicolas Anelka نيكولا انيلكا",
    "Florent Malouda فلوران مالودا",
    "Ashley Cole اشلي كول",
    "Michael Ballack مايكل بالاك",
    "Michael Essien مايكل ايسيان",
    "Petr cech بيتر تشيك",
    "Paulo Ferreira باولو فيريرا",
    "Didier Drogba ديديه دروجبا",
    "Alex اليكس",
    "Ricardo Carvalho ريكاردو كارفاليو",
    "Arjen Robben اريين روبن",
    "Joe Cole جو كول",
    "Wayne Bridge واين بريدج",
    "Claude Makelele كلود ماكيليلي",
    "Geremi جيريمي نجيتاب",
    "Frank Lampard فرانك لامبارد",
    "William Gallas ويليام جالاس",
    "John Terry جون تيري",
    "Marcel Desailly مارسيل ديسايي",
    "Martin Ødegaard مارتين اوديجارد",
    "Gabriel Magalhaes جابريل دوس سانتوس",
    "Kieran Tierney كيران تيرني",
    "Gabriel Martinelli جبريل مارتينيلي",
    "Nicolas Pepe نيكولاس بيبي",
    "Bukayo Saka بوكايو ساكا",
    "Bernd Leno بيرند لينو",
    "Emerick Aubameyang ايميريك اوباميانج",
    "Eddie Nketiah ادي نكيتياه",
    "Alexandre Lacazette الكسندر لاكازيت",
    "Sead Kolasinac سياد كولاشيناتس",
    "Granit Xhaka جرانيت تشاكا",
    "Rob Holding روب هولدينج",
    "Mohamed Elneny محمد النني",
    "Danny Welbeck داني ويلبيك",
    "Alexis Sanchez اليكسيس سانشيز",
    "Hector Bellerin هيكتور بيليرين",
    "Mesut ozil مسعود اوزيل",
    "Santi Cazorla سانتي كازورلا",
    "Mikel Arteta ميكل ارتيتا",
    "Chamberlain تشامبرلين",
    "Enzo Fernandez اينزو فرنانديز",
    "Laurent Koscielny لوران كوشيلني",
    "Wojciech Szczesny فويتشيك شتشيسني",
    "Samir Nasri سمير نصري",
    "Theo Walcott ثيو والكوت",
    "Emmanuel Adebayor ايمانويل اديبايور",
    "Robin van Persie روبين فان بيرسي",
    "Kolo Toure كولو توريه",
    "Gilberto Silva جيلبرتو سيلفا",
    'Patrick Vieira باتريك فييرا',
    "Bruno Fernandes برونو فرنانديز",
    "Aaron Wan Bissaka ارون وان بيساكا",
    "Harry Maguire هاري ماجواير",
    "Mason Greenwood ماسون جرينوود",
    "Diogo Dalot ديوجو دالوت",
    "Fred فريديريكو رودريجيز",
    "Scott McTominay سكوت ماكتوميني",
    "Victor Lindelof فيكتور ليندلوف",
    "Nemanja Matic نيمانيا ماتيتش",
    "Eric Bailly اريك بايلي",
    "Marcus Rashford ماركوس راشفورد",
    "Anthony Martial انتوني مارسيال",
    "Luke Shaw لوك شاو",
    "Marcos Rojo ماركوس روخو",
    "Ander Herrera اندير هيريرا",
    "Jesse Lingard جيسي لينجارد",
    "Daley Blind دالي بليند",
    "Marouane Fellaini مروان فيلايني",
    "Paul Pogba بول بوجبا",
    "Ashley Young اشلي يونج",
    "Phil Jones فيل جونز",
    "David de Gea ديفيد دي خيا",
    "Chris Smalling كريس سمولينج",
    "Javier Hernandez تشيشاريتو",
    "Antonio Valencia انتونيو فالنسيا",
    "Nani ناني",
    "Michael Carrick مايكل كاريك",
    "Patrice Evra باتريس ايفرا",
    "Park Ji sung باك جي سونج",
    "Edwin van der Sar ادوين فان در سار",
    "Wayne Rooney واين روني",
    "Louis Saha لويس ساها",
    "Cristiano Ronaldo كريستيانو رونالدو",
    "Rio Ferdinand ريو فرديناند",
    "Ruud van Nistelrooy رود فان نيستلروي",
    "John OShea جون اوشي",
    "Wes Brown ويس براون",
    "Paul Scholes بول سكولز",
    "David Beckham ديفد بيكام",
    "Gary Neville جاري نيفيل",
    "Peter Schmeichel بيتر شمايكل",
    "Ryan Giggs راين جيجز",
    "Ruben Dias روبن دياس",
    "Joao Cancelo جواو كانسيلو",
    "Rodri رودري",
    "Riyad Mahrez رياض محرز",
    "Aymeric Laporte ايميرك لابورتي",
    "Phil Foden فيل فودين",
    "Kyle Walker كايل ووكر",
    "Bernardo Silva برناردو سيلفا",
    "Ederson ايدرسون مورايس",
    "Gabriel Jesus جابرييل جيسوس",
    "Oleksandr Zinchenko اولكسندر زينتشنكو",
    "Ilkay Gundoğan ايلكاي جوندوجان",
    "Leroy Sane ليروي ساني",
    "John Stones جون ستونز",
    "Kevin De Bruyne كيفين دي بروين",
    "Nicolas Otamendi نيكولاس اوتامندي",
    "Raheem Sterling رحيم ستيرلينج",
    "Fernando فيرناندو فرانسيسكو",
    "Martin Demichelis مارتن ديميكيليس",
    "Fernandinho فرناندينيو",
    "Jesus Navas خيسوس نافاس",
    "Gael Clichy جايل كليشي",
    "Edin Dzeko ادين دجيكو",
    "Aleksandar Kolarov الكساندريه كولاروف",
    "James Milner جيمس ميلنر",
    "David Silva دافيد سيلفا",
    "Joleon Lescott جوليون ليسكوت",
    "Carlos Tevez كارلوس تيفيز",
    "Gareth Barry جاريث باري",
    "Pablo Zabaleta بابلو زاباليتا",
    "Vincent Kompany فينسنت كومباني",
    "Joe Hart جو هارت",
    "Lucas Moura لوكاس مورا",
    "Son Heung min سون هيونج مين",
    "Dele Alli ديلي الي",
    "Paulinho باولينيو",
    "Hugo Loris هوجو لوريس",
    "Mousa Dembele موسي ديمبيلي",
    "Harry Kane هاري كين",
    "Peter Crouch بيتر كراوتش",
    "Aurelien Tchouameni اوريلين تشواميني",
    "Eduardo Camavinga ادواردو كاماڤينجا",
    "David Alaba دافيد الابا",
    "eder Militao ايدر ميليتاو",
    "Rodrygo رودريجو جويس",
    "Ferland Mendy فيرلاند ميندي",
    "Luka Jovic لوكا يوفيتش",
    "Federico Valverde فيديريكو فالفيردي",
    "Vinicius Junior فينيسيوس جونيور",
    "Thibaut Courtois تيبو كورتوا",
    "Dani Ceballos داني سيبايوس",
    "Mariano Diaz ماريانو دياز",
    "Marco Asensio ماركو اسينسيو",
    "Lucas Vazquez لوكاس فاسكيز",
    "Marcos Llorente ماركوس يورينتي",
    "Danilo دانيلو لويز دا سيلفا",
    "Keylor Navas كيلور نافاس",
    "Toni Kroos توني كروس",
    "Dani Carvajal داني كارفاخال",
    "Casemiro كاسيميرو",
    "Isco ايسكو",
    "Gareth Bale غاريث بيل",
    "Asier Illarramendi اسير اياراميندي",
    "Luka Modric لوكا مودريتش",
    "Nacho ناتشو",
    "Raphael Varane رافاييل فاران",
    "Fabio Coentrao فابيو كوينتراو",
    "Jese خيسي رودريجيز",
    "Jose Callejon خوسيه كاييخون",
    "Sami Khedira سامي خضيره",
    "alvaro Morata الفارو موراتا",
    "Karim Benzema كريم بنزيما",
    "Xabi Alonso تشابي الونسو",
    "Raul Albiol راؤول البيول",
    "Kaka ريكاردو كاكا",
    "Lassana Diarra لاسانا ديارا",
    "Esteban Granero استيبان جرانيرو",
    "Rafael van der Vaart رافاييل فان در فارت",
    "Marcelo مارسيلو",
    "Pepe بيبي",
    "Gonzalo Higuain جونزالو هيجواين",
    "Royston Drenthe رويستون درينثي",
    "Fernando Gago فرناندو جاجو",
    "Wesley Sneijder ويسلي سنايدر",
    "Gabriel Heinze جابرييل هاينزه",
    "Mahamadou Diarra محمدو ديارا",
    "Fabio Cannavaro فابيو كانافارو",
    "Miguel Torres ميجيل توريس",
    "Sergio Ramos سيرخيو راموس",
    "Robinho روبينيو",
    "Julio Baptista جوليو بابتيستا",
    "Diego Lopez دييجو لوبيز",
    "alvaro Mejia الفارو ميخيا",
    "alvaro Arbeloa الفارو اربيلوا",
    "Michael Owen مايكل اوين",
    "Javier Portillo خافيير بورتيو",
    "Esteban Cambiasso استيبان كامبياسو",
    "Francisco Pavon فرانسيسكو بافون",
    "Raul Bravo راؤول برافو",
    "Zinedine Zidane زين الدين زيدان",
    "Santiago Solari سانتياجو سولاري",
    "Cesar Sanchez سيزار سانشيز",
    "Flavio Conceicao فلافيو كونسيساو",
    "Pedro Munitis بيدرو مونيتيس",
    "Iker Casillas ايكير كاسيياس",
    "Michel Salgado ميشيل سالجادو",
    "Ivan Helguera ايفان هيليجيرا",
    "Steve McManaman ستيف ماكمانامان",
    "Savio سافيو",
    "Claudio Bravo كلاوديو برافو",
    "Dimitar Berbatov ديميتار برباتوف",
    "Marco Materazzi ماركو ماتيراتزي",
    "Teddy Sheringham تيدي شيرنجهام",
    "Raul Jimenez راؤول خيمينيز",
    "Jerome Boateng جيروم بواتينج",
    "Ivan Campo ايفان كامبو",
    "Robert Jarni روبيرت يارني",
    "Fernando Morientes فرناندو مورينتس",
    "Aitor Karanka ايتور كارانكا",
    "Christian Karembeu كريستيان كاريمبو",
    "Roberto Carlos روبرتو كارلوس",
    "Bodo Illgner بودو اليغنر",
    "Christian Panucci كريستيان بانوتشي",
    "Davor suker دافور شوكر",
    "Clarence Seedorf كلارنس سيدورف",
    "Predrag Mijatovic بريدراج مياتوفيتش",
    "Victor Sanchez فيكتور سانشيز",
    "Guti جوتي",
    "Raul راؤول جونزاليس",
    "Ivan Zamorano ايفان زامورانو",
    "Fernando Hierro فرناندو هييرو",
    "Santillana كارلوس سانتيانا",
    "Ferenc Puskas فيرينتس بوشكاش",
    "Paco Gento باكو خينتو",
    "Ricardo Zamora ريكاردو زامورا",
    "Santiago Bernabeu سانتياجو بيرنابيو",
    "Diogo Jota دييجو جوتا",
    "Fabinho فابينيو تافاريس",
    "Naby Keita نابي كيتا",
    "Alisson Becker اليسون بيكر",
    "Virgil van Dijk فيرجيل فان دايك",
    "Andrew Robertson اندرو روبرتسون",
    "Mohamed Salah محمد صلاح",
    "Joel Matip جويل ماتيب",
    "Sadio Mane ساديو ماني",
    "Georginio Wijnaldum جورجينيو فينالدوم",
    "Divock Origi ديفوك اوريجي",
    "Joe Gomez جو جوميز",
    "Roberto Firmino روبرتو فيرمينو",
    "Nathaniel Clyne ناثانييل كلاين",
    "Emre Can امري تشان",
    "Alberto Moreno البرتو مورينو",
    "Adam Lallana ادم لالانا",
    "Dejan Lovren ديان لوفرين",
    "Simon Mignolet سيمون مينيوليه",
    "Philippe Coutinho فيليبي كوتينيو",
    "Jordan Henderson جوردان هيندرسون",
    "Steven Gerrard ستيڤين چيرارد",
    "Jamie Carragher جيمي كاراجر",
    "Robbie Fowler روبي فاولر",
    "Arturo Vidal ارتورو فيدال",
    "Luca Toni لوكا توني",
    "Corentin Tolisso كورينتين توليسو",
    "Thiago Alcantara تياجو الكانتارا",
    "Niklas Sule نيكلاس شوله",
    "Xherdan Shaqiri شيردان شاكيري",
    "Bastian Schweinsteiger باستيان شفاينشتايجر",
    "Franck Ribery فرانك ريبيري",
    "Rafinha رافينيا",
    "Lukas Podolski لوكاس بودولسكي",
    "Benjamin Pavard بنجامين بافار",
    "Manuel Neuer مانويل نوير",
    "Jamal Musiala جمال موسيالا",
    "Thomas Muller توماس مولر",
    "Gerd Muller جيرد مولر",
    "Mario Mandzukic ماريو ماندجوكيتش",
    "Robert Lewandowski روبرت ليفاندوفسكي",
    "Philipp Lahm فيليب لام",
    "Miroslav Klose ميروسلاڤ كلوزه",
    "Joshua Kimmich جوشوا كيميش",
    "Oliver Kahn اوليفر كان",
    "Mario Gotze ماريو جوتزه",
    'Bentancur بينتانكور',
    "Leon Goretzka ليون جوريتسكا",
    "Mario Gomez ماريو جوميز",
    "Serge Gnabry سيرجي جنابري",
    "Hansi Flick هانس فليك",
    "Alphonso Davies الفونسو ديفيز",
    "Douglas Costa دوجلاس كوستا",
    "Kingsley Coman كينجسلي كومان",
    "Marco Verratti ماركو فيراتي",
    "Marquinhos ماركينيوس",
    "Moise Kean مويس كين",
    "Ivan Cordoba ايفان كوردوبا",
    "Sylvain Armand سيلفان ارمان",
    "Cavani كافاني",
    "Blaise Matuidi بليز ماتويدي",
    "angel Di Maria انخيل دي ماريا",
    "Presnel Kimpembe بريسنيل كيمبيمبي",
    "Adrien Rabiot ادريان رابيو",
    "Maxwell ماكسويل",
    "Serge Aurier سيرج اورييه",
    "Javier Pastore خافيير بستوري",
    "Jese Rodriguez خيسيه رودريجيز",
    "Gianluigi Buffon جيانلويجي بوفون",
    "Danilo Luiz da Silva دانيلو لويز دا سيلفا",
    "Davide Santon دافيدي سانتون",
    "Nicolas Burdisso نيكولاس بورديسو",
    "Juan Jesus خوان خيسوس",
    "Hugo Campagnaro هوجو كامبانيارو",
    "Javier Zanetti خافيير زانيتي",
    "Giuseppe Meazza جوزيبي ميازا",
    "Christian Vieri كريستيان فييري",
    "Sergio Ramos سيرجيو راموس",
    "Fernando Torres فيرناندو توريس",
    "Kaka كاكا",
    "Ezequiel Lavezzi ازيكيل لافيزي",
    "Thiago Silva تياغو سيلفا",
    "Julian Draxler يوليان دراكسلر",
    "Arthur Melo ارثر ميلو",
    "Emerson Palmieri ايمرسون بالميري",
    "Franz Beckenbauer فرانتس بكنباور",
    "Zlatan Ibrahimovic زلتان ابراهيموفيتش",
    "Leandro Paredes لياندرو باريديس",
    "Marco Reus ماركو رويس",
    "Achraf Hakimi اشرف حكيمي",
    "Jadon Sancho جيدون سانشو",
    "Ivan Perisic ايفان بيريشيتش",
    "Mats Hummels ماتس هوملز",
    "Nuri Sahin نوري شاهين",
    "Francesco Toldo فرانشيسكو تولدو",
    "Diego Milito دييجو ميليتو",
    "Lautaro Martinez لاوتارو مارتينيز",
    "Romelu Lukaku روميلو لوكاكو",
    "Julio Cesar جوليو سيزار",
    "Mauro Icardi ماورو ايكاردي",
    "Hernan Crespo هرنان كرسبو",
    "Marcelo Brozovic مارسيلو بروزوفيتش",
    "Alessandro Bastoni اليساندرو باستوني",
    "Nicolo Barella نيكولو باريلا",
    "Adriano ادريانو",
    "Sandro Tonali ساندرو تونالي",
    "Brahim Diaz براهيم دياز",
    "Theo Hernandez تيو هرنانديز",
    "Rafael Leao رفائيل لياو",
    "Ismael Bennacer اسماعيل بن ناصر",
    "Franck Kessie فرانك كيسي",
    "Gianluigi Donnarumma جانلويجي دوناروما",
    "Stephan El Shaarawy ستيفان الشعراوي",
    "Luca Antonini لوكا انتونيني",
    "Mathieu Flamini ماتيو فلاميني",
    "Alexandre Pato الكساندريه باتو",
    "Cafu كافو",
    "Alessandro Nesta اليساندرو نيستا",
    "Andrea Pirlo اندريا بيرلو",
    "Filippo Inzaghi فيليبو انزاجي",
    "Dida ديدا",
    "Gennaro Gattuso جنارو جاتوزو",
    "Serginho سيرجينهو",
    "Sebastiano Rossi سيباستيانو روسي",
    "Frank Rijkaard فرانك ريكارد",
    "Marco van Basten ماركو فان باستن",
    "Carlo Ancelotti كارلو انشيلوتي",
    "Alessandro Costacurta الساندرو كوستاكورتا",
    "Paolo Maldini باولو مالديني",
    "David Trezeguet دافيد تريزيجيه",
    "Alex Sandro اليكس ساندرو",
    "Miralem Pjanic ميراليم بيانيتش",
    "Claudio Marchisio كلوديو ماركيزيو",
    "Paulo Dybala باولو ديبالا",
    "Danilo دانيلو",
    "Juan Cuadrado خوان كوادرادو",
    "Antonio Conte انطونيو كونتي",
    "Giorgio Chiellini جورجيو كيلليني",
    "Fabio Capello فابيو كابيلو",
    "Gianluigi Buffon جيانلويجي بوفون",
    "Leonardo Bonucci ليوناردو بونوتشي",
    "Andrea Barzagli اندريا بارزالي",
    "Roberto Baggio روبرتو باجو",
    "Kostas Manolas كوستاس مانولاس",
    "Radja Nainggolan راجا ناينجولان",
    "Alessandro Florenzi اليساندرو فلورينزي",
    "Mancini مانسيني",
    "Daniele De Rossi دانييلي دي روسي",
    "Antonio Cassano انطونيو كاسانو",
    "Victor Osimhen فيكتور اوسيمين",
    "Kalidou Koulibaly خاليدو كوليبالي",
    "Thomas Lemar توماس ليمار",
    "Lucio لوسيو",
    "Manuel Akanji مانويل اكانجي",
    "Unai Simon اوناي سيمون",
    "Yerry Mina ياري مينا",
    "Alexander Isak الكسندر ايساك",
    "Diego Calderon دييغو كالديرون",
    "Paco Alcacer باكو الكاسير",
    "Loris Karius لوريس كاريوس",
    "Raphael Guerreiro رافاييل غيريرو",
    "Thorgan Hazard تورجان هازار",
    "James Ward Prowse جيمس وارد براوس",
    "Jamie Vardy جيمي فاردي",
    "Dennis Bergkamp دينيس بيركامب",
    "Alan Shearer الان شيرر",
    "Kylian Mbappe كيليان مبابي",
    "Pele بيليه",
    "Thierry Henry تييري هنري",
    "Francesco Totti فرانشيسكو توتي",
    "Diego Forlan دييغو فورلان",
    "Ciro Immobile تشيرو ايموبيلي",
    "Erling Haaland ارلينغ هالاند",
    "Lionel Messi ليونيل ميسي",
    "Ronaldinho رونالدينيو",
    "Andriy Shevchenko اندريه شيفتشينكو",
    "Pavel Nedved بافل نيدفيد",
    "George Weah جورج ويا",
    "Ruud Gullit رود خوليت",
    "Michel Platini ميشيل بلاتيني",
    "Raymond Kopa ريموند كوبا",
    "Alfredo Di Stefano الفريدو دي ستيفانو",
    "Paolo Rossi باولو روسي",
    "James Rodriguez خاميس رودريغيز",
    "Andre Ayew كريستيان اريكسن",
    "Christian Eriksen اندريه ايو",
    "Antony انتوني",
    "Matthijs de Ligt ماتيس دي ليخت",
    "Joao Felix جواو فيليكس",
    "Pedri بيدري",
    "Gavi جافي",
    "Julian alvarez جوليان الفاريز",
    "Timo Werner تيمو فيرنر",
    "Nico Gonzalez نيكو غونزاليس",
  ];
}